name: dl
channels:
  - pytorch
  - conda-forge
dependencies:
  - autopep8=1.4.4
  - flake8=4.0.1
  - notebook=6.4.12
  - pillow=9.1.1
  - pip=22.2
  - python=3.10.4
  - pytorch=1.12.0
  - pip:
      - feature_transform==0.4.1
      - hydra-core==1.2.0
      - hydra-optuna-sweeper==1.2.0
      - pytest-cov==3.0.0
      - pytest==7.1.3
      - pytorch-lightning==1.6.5
      - torcharc==1.2.1
      - -e .
