name: dl
channels:
  - pytorch
  - conda-forge
dependencies:
  - notebook=6.4.12
  - pip=22.2
  - python=3.10.4
  - pytorch=2.0.0
  - pip:
      - feature_transform==0.4.1
      - hydra-core==1.3.2
      - hydra-optuna-sweeper==1.2.0
      - pytest-cov==3.0.0
      - pytest==7.1.3
      - pytorch-lightning==2.0.2
      - tensorboard==2.13.0
      - torcharc==1.2.1
      - torchmetrics==0.11.4
      - -e .
