# PyTorch LightningDataModule config
datamodule:
  # Heart Failure Prediction Dataset from https://www.kaggle.com/datasets/fedesoriano/heart-failure-prediction
  # URL or local path to download raw data
  csv: https://gist.githubusercontent.com/kengz/e4849ec4f3aca4ae054b38e1410a76d5/raw/fa3548691f64e5b984ce284e1636d23ba15bf195/heart.csv
  data_filename: mode2data.pkl
  train_frac: 0.8 # train/val split
dataloader:
  batch_size: 64
