# PyTorch LightningModule configs
# model architecture using TorchArc
arc:
  dag_in_shape:
    main: [19]
  main:
    type: Linear
    layers: [64, 32]
    batch_norm: true
    activation: ReLU
    dropout: 0.01
    init:
      type: normal_
      std: 0.01
  out:
    type: Linear
    out_features: 1

# criterion (loss function)
loss:
  type: BCEWithLogitsLoss
  pos_weight: 10.0

# optimizer
optim:
  type: Adam
  lr: 3e-4

# torchmetrics.MetricCollection for evaluation
metric:
  # e.g. Precision: {num_classes: 3, average: 'macro'}
  Accuracy:
  Precision:
  Recall:
  F1Score:
# which of the metric above to return from main() for Optuna sweep
optuna_metric: F1Score

# Lighting Trainer
trainer:
  max_epochs: 10 # set to None to auto-stop on convergence
  accelerator: auto # will switch to GPU if available
