# config for lightning-related modules
datamodule:
  # dataset for stroke prediction cloned from Kaggle https://www.kaggle.com/datasets/fedesoriano/stroke-prediction-dataset
  # url to GitHub gist to download the data
  url: https://gist.githubusercontent.com/kengz/833544b48224922b86215d645a8c8b71/raw/cec0340503d82d270821e03254993b6dede60afb/healthcare-dataset-stroke-data.csv
  data_filename: mode2data.pkl
  train_frac: 0.8 # train/val split
dataloader:
  batch_size: 64

arc:
  dag_in_shape:
    main: [19]
  main:
    type: Linear
    layers: [64, 32]
    batch_norm: true
    activation: ReLU
    dropout: 0.04
    init:
      type: normal_
      std: 0.01
  out:
    type: Linear
    out_features: 1
loss: binary_cross_entropy_with_logits
optim:
  type: Adam
  lr: 3e-4
trainer:
  max_epochs: 100 # set to None to auto-stop on convergence
  accelerator: auto # will switch to GPU if available
resume: false # resume training from the latest checkpoint
