# config for feature_transform
transform:
  x:
    transformers:
      - transformer:
          preprocessing.RobustScaler: {}
        columns: [Age, RestingBP, Cholesterol, MaxHR]
      - transformer:
          preprocessing.OneHotEncoder:
            sparse_output: false
        columns: [Sex, ChestPainType, RestingECG, ExerciseAngina, ST_Slope]
      - transformer:
          preprocessing.PowerTransformer: {}
        columns: [FastingBS, Oldpeak]
    n_jobs: -1
  y:
    transformers:
      - transformer: passthrough
        columns: [HeartDisease]
