# @package hydra.sweeper
# doc: https://hydra.cc/docs/plugins/optuna_sweeper/
sampler:
  seed: 42
study_name: dl-tune
direction: maximize
storage: null
n_trials: 100
n_jobs: 1
params:
  # use dot-notation for nested config fields
  arc.main.layers: choice([8], [8, 8], [8, 8, 8], [16, 16], [32, 32])
  arc.main.dropout: interval(0.0, 0.3)
  loss.pos_weight: interval(1.0, 10.0)
  optim.type: choice(Adam, RMSprop, SGD)
  optim.lr: tag(log, interval(1e-5, 1e-1))
