name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: ["**"]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: pip

      - uses: liskin/gh-problem-matcher-wrap@v1
        with:
          action: add
          linters: flake8

      - name: Lint with flake8
        run: |
          pip install flake8
          # exit-zero treats all errors as warnings.
          flake8 . --ignore=E501 --count --exit-zero --statistics

      - uses: liskin/gh-problem-matcher-wrap@v1
        with:
          action: remove
          linters: flake8

  build:
    needs: lint
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v3

      - name: Cache conda
        uses: actions/cache@v2
        env:
          CACHE_UPLOAD_CHUNK_SIZE: 67108864
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{
            hashFiles('etc/example-environment.yml') }}

      - name: Create Conda env
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: dl
          environment-file: environment.yml
          miniforge-version: latest
          use-only-tar-bz2: true # for caching

      - uses: liskin/gh-problem-matcher-wrap@v1
        with:
          action: add
          linters: pytest

      - name: Run tests
        run: |
          pip install wheel
          pytest | tee pytest-coverage.txt

      - name: Post coverage to PR comment
        uses: coroo/pytest-coverage-commentator@v1.0.2

      - uses: liskin/gh-problem-matcher-wrap@v1
        with:
          action: add
          linters: pytest
